name: lfads-torch
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10  # Specify your preferred Python version
  - pytorch=2.1.2
  - torchvision=0.16.2
  - torchaudio=2.1.2
  - pip
  - pip:
    - lightning==2.1.0
    - torchmetrics==1.2.0
    - hydra-core==1.3.2
    - h5py
    - pre-commit
    - black
    - isort
    - flake8
    - "ray[tune]==2.1.0"
    - "pydantic<2.0.0"
    - matplotlib
    - wandb
    - pybind11>=2.12
    - scikit-learn
    - ipykernel
    - seaborn
    - numpy<2
    - -e .
